name: mhu_dart_commons
version: 1.0.5
description: Common utilities used in my Dart and Flutter projects
repository: https://github.com/maprohu/mhu_dart_commons

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
