name: mhu_dart_commons
version: 1.0.9
description: Common utilities used in my Dart and Flutter projects
repository: https://github.com/maprohu/mhu_dart_commons

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  mhu_dart_builder:
    path: ../mhu_dart_builder

dependencies:
  mhu_dart_annotation: ^1.0.1

  path: ^1.8.3
  rxdart: ^0.27.7
  collection: ^1.17.1
  logger: ^1.4.0
  protobuf: ^3.0.0
  cross_file: ^0.3.3+4
  fast_immutable_collections: ^9.1.5
  isar: ^3.1.0+1
  freezed_annotation: ^2.4.1
  decimal: ^2.3.3
  fixnum: ^1.1.0
  intl: ^0.18.1
  timeago: ^3.5.0
  recase: ^4.1.0

dev_dependencies:
  mhu_dart_builder: ^1.0.3
  
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  freezed: ^2.4.1
